name: Main
# if pushed run
on: [push]
# job
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: cd /www/wwwroot/otpiq.rstacode.dev/ && git checkout --ours ./ && git pull origin main && composer install && php artisan migrate:fresh --seed && php artisan optimize:clear && php artisan key:generate && npm install && npm run build && php artisan icons:cache
